name: SonarQube Analysis

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  SONAR_PROJECT_KEY: openautomate-botagent
  SONAR_PROJECT_NAME: openautomate-botagent
  SONAR_HOST_URL: http://sonar.openautomate.me

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin \
            /k:"$SONAR_PROJECT_KEY" \
            /n:"$SONAR_PROJECT_NAME" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/OpenAutomate.BotAgent.UI/**,**/OpenAutomate.BotAgent.Installer/**"

      - name: Build solution
        run: |
          dotnet restore OpenAutomate.BotAgent.sln
          dotnet build OpenAutomate.BotAgent.sln --no-restore

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 